// Dataset 118 Unsur Tabel Periodik Kimia (Bahasa Indonesia)
const elementsData = [
  {
    number: 1,
    symbol: "H",
    name: "Hidrogen",
    latinName: "Hydrogenium",
    mass: 1.008,
    category: "nonmetal",
    categoryName: "Non-logam",
    state: "gas",
    group: 1,
    period: 1,
    block: "s",
    shells: [1],
    config: "1s¹",
    electronegativity: 2.20,
    meltingPoint: -259.16,
    boilingPoint: -252.87,
    density: 0.00008988,
    discovered: 1766,
    discoverer: "Henry Cavendish",
    summary: "Hidrogen adalah unsur paling ringan dan paling melimpah di alam semesta, membentuk sekitar 75% dari massa elemental bintang dan planet gas."
  },
  {
    number: 2,
    symbol: "He",
    name: "Helium",
    latinName: "Helium",
    mass: 4.0026,
    category: "noble-gas",
    categoryName: "Gas Mulia",
    state: "gas",
    group: 18,
    period: 1,
    block: "s",
    shells: [2],
    config: "1s²",
    electronegativity: null,
    meltingPoint: -272.2,
    boilingPoint: -268.93,
    density: 0.0001785,
    discovered: 1868,
    discoverer: "Pierre Janssen, Norman Lockyer",
    summary: "Helium adalah gas mulia tak berwarna dan tak berbau. Unsur ini adalah unsur kedua paling melimpah dan kedua paling ringan di alam semesta teramati."
  },
  {
    number: 3,
    symbol: "Li",
    name: "Litium",
    latinName: "Lithium",
    mass: 6.94,
    category: "alkali-metal",
    categoryName: "Logam Alkali",
    state: "solid",
    group: 1,
    period: 2,
    block: "s",
    shells: [2, 1],
    config: "[He] 2s¹",
    electronegativity: 0.98,
    meltingPoint: 180.5,
    boilingPoint: 1342,
    density: 0.534,
    discovered: 1817,
    discoverer: "Johan August Arfwedson",
    summary: "Litium adalah logam alkali yang lunak dan berwarna putih perak. Litium merupakan logam paling ringan dan memiliki massa jenis paling rendah di antara unsur padat."
  },
  {
    number: 4,
    symbol: "Be",
    name: "Berilium",
    latinName: "Beryllium",
    mass: 9.0122,
    category: "alkaline-earth",
    categoryName: "Alkali Tanah",
    state: "solid",
    group: 2,
    period: 2,
    block: "s",
    shells: [2, 2],
    config: "[He] 2s²",
    electronegativity: 1.57,
    meltingPoint: 1287,
    boilingPoint: 2469,
    density: 1.85,
    discovered: 1798,
    discoverer: "Louis-Nicolas Vauquelin",
    summary: "Berilium adalah logam alkali tanah relatif langka di alam semesta. Berilium relatif kaku, kuat, dan ringan, banyak digunakan dalam paduan industri kedirgantaraan."
  },
  {
    number: 5,
    symbol: "B",
    name: "Boron",
    latinName: "Borum",
    mass: 10.81,
    category: "metalloid",
    categoryName: "Metaloid",
    state: "solid",
    group: 13,
    period: 2,
    block: "p",
    shells: [2, 3],
    config: "[He] 2s² 2p¹",
    electronegativity: 2.04,
    meltingPoint: 2076,
    boilingPoint: 3927,
    density: 2.34,
    discovered: 1808,
    discoverer: "Joseph Louis Gay-Lussac, Louis Jacques Thénard",
    summary: "Boron adalah metaloid yang jarang ditemukan secara murni di alam. Digunakan secara luas dalam pembuatan kaca borosilikat (Pyrex) dan semikonduktor."
  },
  {
    number: 6,
    symbol: "C",
    name: "Karbon",
    latinName: "Carbonium",
    mass: 12.011,
    category: "nonmetal",
    categoryName: "Non-logam",
    state: "solid",
    group: 14,
    period: 2,
    block: "p",
    shells: [2, 4],
    config: "[He] 2s² 2p²",
    electronegativity: 2.55,
    meltingPoint: 3550,
    boilingPoint: 4027,
    density: 2.267,
    discovered: "Kuno",
    discoverer: "Tidak diketahui",
    summary: "Karbon adalah dasar dari seluruh kehidupan organik yang diketahui di Bumi. Memiliki allotrop seperti intan yang sangat keras dan grafit yang konduktif."
  },
  {
    number: 7,
    symbol: "N",
    name: "Nitrogen",
    latinName: "Nitrogenium",
    mass: 14.007,
    category: "nonmetal",
    categoryName: "Non-logam",
    state: "gas",
    group: 15,
    period: 2,
    block: "p",
    shells: [2, 5],
    config: "[He] 2s² 2p³",
    electronegativity: 3.04,
    meltingPoint: -210.0,
    boilingPoint: -195.79,
    density: 0.0012506,
    discovered: 1772,
    discoverer: "Daniel Rutherford",
    summary: "Nitrogen menyusun sekitar 78% dari atmosfer Bumi. Merupakan komponen penting dalam asam amino, protein, dan asam nukleat (DNA/RNA)."
  },
  {
    number: 8,
    symbol: "O",
    name: "Oksigen",
    latinName: "Oxygenium",
    mass: 15.999,
    category: "nonmetal",
    categoryName: "Non-logam",
    state: "gas",
    group: 16,
    period: 2,
    block: "p",
    shells: [2, 6],
    config: "[He] 2s² 2p⁴",
    electronegativity: 3.44,
    meltingPoint: -218.79,
    boilingPoint: -182.96,
    density: 0.001429,
    discovered: 1774,
    discoverer: "Joseph Priestley, Carl Wilhelm Scheele",
    summary: "Oksigen adalah unsur paling melimpah ketiga di alam semesta dan sangat vital bagi respirasi sebagian besar makhluk hidup di Bumi serta pembakaran."
  },
  {
    number: 9,
    symbol: "F",
    name: "Fluorin",
    latinName: "Fluorum",
    mass: 18.998,
    category: "halogen",
    categoryName: "Halogen",
    state: "gas",
    group: 17,
    period: 2,
    block: "p",
    shells: [2, 7],
    config: "[He] 2s² 2p⁵",
    electronegativity: 3.98,
    meltingPoint: -219.67,
    boilingPoint: -188.11,
    density: 0.001696,
    discovered: 1886,
    discoverer: "Henri Moissan",
    summary: "Fluorin adalah unsur yang paling reaktif secara kimia dan paling elektronegatif dari semua unsur. Sangat berbahaya dalam bentuk gas murni."
  },
  {
    number: 10,
    symbol: "Ne",
    name: "Neon",
    latinName: "Neon",
    mass: 20.180,
    category: "noble-gas",
    categoryName: "Gas Mulia",
    state: "gas",
    group: 18,
    period: 2,
    block: "p",
    shells: [2, 8],
    config: "[He] 2s² 2p⁶",
    electronegativity: null,
    meltingPoint: -248.59,
    boilingPoint: -246.08,
    density: 0.0009002,
    discovered: 1898,
    discoverer: "William Ramsay, Morris Travers",
    summary: "Neon memberikan kilatan cahaya oranye-merah yang khas ketika digunakan pada tabung pelepasan listrik tegangan tinggi (lampu neon)."
  },
  {
    number: 11,
    symbol: "Na",
    name: "Natrium",
    latinName: "Natrium",
    mass: 22.990,
    category: "alkali-metal",
    categoryName: "Logam Alkali",
    state: "solid",
    group: 1,
    period: 3,
    block: "s",
    shells: [2, 8, 1],
    config: "[Ne] 3s¹",
    electronegativity: 0.93,
    meltingPoint: 97.794,
    boilingPoint: 882.94,
    density: 0.968,
    discovered: 1807,
    discoverer: "Humphry Davy",
    summary: "Natrium adalah logam alkali yang sangat reaktif. Beraksi hebat dengan air. Merupakan komponen utama dari garam dapur (NaCl)."
  },
  {
    number: 12,
    symbol: "Mg",
    name: "Magnesium",
    latinName: "Magnesium",
    mass: 24.305,
    category: "alkaline-earth",
    categoryName: "Alkali Tanah",
    state: "solid",
    group: 2,
    period: 3,
    block: "s",
    shells: [2, 8, 2],
    config: "[Ne] 3s²",
    electronegativity: 1.31,
    meltingPoint: 650,
    boilingPoint: 1090,
    density: 1.738,
    discovered: 1755,
    discoverer: "Joseph Black",
    summary: "Magnesium adalah logam berkilau perak yang sangat ringan. Merupakan atom pusat pada klorofil yang memungkinkan fotosintesis pada tumbuhan."
  },
  {
    number: 13,
    symbol: "Al",
    name: "Aluminium",
    latinName: "Aluminium",
    mass: 26.982,
    category: "post-transition",
    categoryName: "Pasca-Transisi",
    state: "solid",
    group: 13,
    period: 3,
    block: "p",
    shells: [2, 8, 3],
    config: "[Ne] 3s² 3p¹",
    electronegativity: 1.61,
    meltingPoint: 660.32,
    boilingPoint: 2470,
    density: 2.70,
    discovered: 1825,
    discoverer: "Hans Christian Ørsted",
    summary: "Aluminium adalah logam berlimpah di kerak bumi. Memiliki ketahanan korosi yang sangat baik dan massa jenis rendah, populer dalam konstruksi dan kemasan."
  },
  {
    number: 14,
    symbol: "Si",
    name: "Silikon",
    latinName: "Silicium",
    mass: 28.085,
    category: "metalloid",
    categoryName: "Metaloid",
    state: "solid",
    group: 14,
    period: 3,
    block: "p",
    shells: [2, 8, 4],
    config: "[Ne] 3s² 3p²",
    electronegativity: 1.90,
    meltingPoint: 1414,
    boilingPoint: 3265,
    density: 2.329,
    discovered: 1823,
    discoverer: "Jöns Jacob Berzelius",
    summary: "Silikon adalah bahan utama dalam pembuatan chip semikonduktor, mikroprosesor, dan panel surya. Unsur kedua paling melimpah di kerak bumi."
  },
  {
    number: 15,
    symbol: "P",
    name: "Fosforus",
    latinName: "Phosphorus",
    mass: 30.974,
    category: "nonmetal",
    categoryName: "Non-logam",
    state: "solid",
    group: 15,
    period: 3,
    block: "p",
    shells: [2, 8, 5],
    config: "[Ne] 3s² 3p³",
    electronegativity: 2.19,
    meltingPoint: 44.15,
    boilingPoint: 280.5,
    density: 1.823,
    discovered: 1669,
    discoverer: "Hennig Brand",
    summary: "Fosforus terdapat dalam bentuk fosfor putih yang mudah terbakar dan fosfor merah yang stabil pada korek api. Penting untuk tulang dan ATP seluler."
  },
  {
    number: 16,
    symbol: "S",
    name: "Belerang",
    latinName: "Sulphur",
    mass: 32.06,
    category: "nonmetal",
    categoryName: "Non-logam",
    state: "solid",
    group: 16,
    period: 3,
    block: "p",
    shells: [2, 8, 6],
    config: "[Ne] 3s² 3p⁴",
    electronegativity: 2.58,
    meltingPoint: 115.21,
    boilingPoint: 444.6,
    density: 2.07,
    discovered: "Kuno",
    discoverer: "Tidak diketahui",
    summary: "Belerang adalah padatan kuning cerah pada suhu ruang. Digunakan dalam vulkanisasi karet, pembuatan asam sulfat, dan pupuk."
  },
  {
    number: 17,
    symbol: "Cl",
    name: "Klorin",
    latinName: "Chlorum",
    mass: 35.45,
    category: "halogen",
    categoryName: "Halogen",
    state: "gas",
    group: 17,
    period: 3,
    block: "p",
    shells: [2, 8, 7],
    config: "[Ne] 3s² 3p⁵",
    electronegativity: 3.16,
    meltingPoint: -101.5,
    boilingPoint: -34.04,
    density: 0.003214,
    discovered: 1774,
    discoverer: "Carl Wilhelm Scheele",
    summary: "Klorin adalah gas beracun berwarna kuning-hijau. Banyak digunakan sebagai disinfektan air minum, kolam renang, dan bahan pemutih."
  },
  {
    number: 18,
    symbol: "Ar",
    name: "Argon",
    latinName: "Argon",
    mass: 39.948,
    category: "noble-gas",
    categoryName: "Gas Mulia",
    state: "gas",
    group: 18,
    period: 3,
    block: "p",
    shells: [2, 8, 8],
    config: "[Ne] 3s² 3p⁶",
    electronegativity: null,
    meltingPoint: -189.34,
    boilingPoint: -185.85,
    density: 0.001784,
    discovered: 1894,
    discoverer: "Lord Rayleigh, William Ramsay",
    summary: "Argon adalah gas mulia paling melimpah di atmosfer Bumi (~0.93%). Digunakan sebagai atmosfer inert pada pengelasan dan bola lampu."
  },
  {
    number: 19,
    symbol: "K",
    name: "Kalium",
    latinName: "Kalium",
    mass: 39.098,
    category: "alkali-metal",
    categoryName: "Logam Alkali",
    state: "solid",
    group: 1,
    period: 4,
    block: "s",
    shells: [2, 8, 8, 1],
    config: "[Ar] 4s¹",
    electronegativity: 0.82,
    meltingPoint: 63.5,
    boilingPoint: 759,
    density: 0.89,
    discovered: 1807,
    discoverer: "Humphry Davy",
    summary: "Kalium adalah logam alkali yang lunak dan sangat reaktif. Penting untuk fungsi saraf dan keseimbangan cairan pada sel tubuh makhluk hidup."
  },
  {
    number: 20,
    symbol: "Ca",
    name: "Kalsium",
    latinName: "Calcium",
    mass: 40.078,
    category: "alkaline-earth",
    categoryName: "Alkali Tanah",
    state: "solid",
    group: 2,
    period: 4,
    block: "s",
    shells: [2, 8, 8, 2],
    config: "[Ar] 4s²",
    electronegativity: 1.00,
    meltingPoint: 842,
    boilingPoint: 1484,
    density: 1.55,
    discovered: 1808,
    discoverer: "Humphry Davy",
    summary: "Kalsium adalah unsur penting dalam pembentukan tulang dan gigi pada manusia dan hewan. Merupakan logam paling melimpah di tubuh manusia."
  },
  {
    number: 21,
    symbol: "Sc",
    name: "Skandium",
    latinName: "Scandium",
    mass: 44.956,
    category: "transition-metal",
    categoryName: "Logam Transisi",
    state: "solid",
    group: 3,
    period: 4,
    block: "d",
    shells: [2, 8, 9, 2],
    config: "[Ar] 3d¹ 4s²",
    electronegativity: 1.36,
    meltingPoint: 1541,
    boilingPoint: 2836,
    density: 2.985,
    discovered: 1879,
    discoverer: "Lars Fredrik Nilson",
    summary: "Skandium adalah logam transisi lunak. Paduan skandium-aluminium digunakan pada rangka pesawat tempur dan peralatan olahraga kelas tinggi."
  },
  {
    number: 22,
    symbol: "Ti",
    name: "Titanium",
    latinName: "Titanium",
    mass: 47.867,
    category: "transition-metal",
    categoryName: "Logam Transisi",
    state: "solid",
    group: 4,
    period: 4,
    block: "d",
    shells: [2, 8, 10, 2],
    config: "[Ar] 3d² 4s²",
    electronegativity: 1.54,
    meltingPoint: 1668,
    boilingPoint: 3287,
    density: 4.506,
    discovered: 1791,
    discoverer: "William Gregor",
    summary: "Titanium terkenal karena kekuatan setara baja namun dengan bobot yang jauh lebih ringan dan sangat tahan terhadap korosi air laut serta klorin."
  },
  {
    number: 23,
    symbol: "V",
    name: "Vanadium",
    latinName: "Vanadium",
    mass: 50.942,
    category: "transition-metal",
    categoryName: "Logam Transisi",
    state: "solid",
    group: 5,
    period: 4,
    block: "d",
    shells: [2, 8, 11, 2],
    config: "[Ar] 3d³ 4s²",
    electronegativity: 1.63,
    meltingPoint: 1910,
    boilingPoint: 3407,
    density: 6.11,
    discovered: 1801,
    discoverer: "Andrés Manuel del Río",
    summary: "Vanadium ditambahkan pada baja untuk menghasilkan paduan baja vanadium yang sangat kuat dan tahan aus, biasa dipakai pada alat-alat pertukangan."
  },
  {
    number: 24,
    symbol: "Cr",
    name: "Kromium",
    latinName: "Chromium",
    mass: 51.996,
    category: "transition-metal",
    categoryName: "Logam Transisi",
    state: "solid",
    group: 6,
    period: 4,
    block: "d",
    shells: [2, 8, 13, 1],
    config: "[Ar] 3d⁵ 4s¹",
    electronegativity: 1.66,
    meltingPoint: 1907,
    boilingPoint: 2671,
    density: 7.19,
    discovered: 1797,
    discoverer: "Louis-Nicolas Vauquelin",
    summary: "Kromium adalah komponen utama penyusun stainless steel yang memberikan efek mengkilap dan perlindungan anti-karat."
  },
  {
    number: 25,
    symbol: "Mn",
    name: "Mangan",
    latinName: "Manganum",
    mass: 54.938,
    category: "transition-metal",
    categoryName: "Logam Transisi",
    state: "solid",
    group: 7,
    period: 4,
    block: "d",
    shells: [2, 8, 13, 2],
    config: "[Ar] 3d⁵ 4s²",
    electronegativity: 1.55,
    meltingPoint: 1246,
    boilingPoint: 2061,
    density: 7.21,
    discovered: 1774,
    discoverer: "Johan Gottlieb Gahn",
    summary: "Mangan sangat krusial dalam pembuatan baja industri untuk meningkatkan kekerasan dan kekuatan impak."
  },
  {
    number: 26,
    symbol: "Fe",
    name: "Besi",
    latinName: "Ferrum",
    mass: 55.845,
    category: "transition-metal",
    categoryName: "Logam Transisi",
    state: "solid",
    group: 8,
    period: 4,
    block: "d",
    shells: [2, 8, 14, 2],
    config: "[Ar] 3d⁶ 4s²",
    electronegativity: 1.83,
    meltingPoint: 1538,
    boilingPoint: 2862,
    density: 7.874,
    discovered: "Kuno",
    discoverer: "Tidak diketahui",
    summary: "Besi adalah logam yang paling banyak digunakan di dunia. Merupakan inti dari hemoglobin yang mengangkut oksigen dalam darah manusia."
  },
  {
    number: 27,
    symbol: "Co",
    name: "Kobalt",
    latinName: "Cobaltum",
    mass: 58.933,
    category: "transition-metal",
    categoryName: "Logam Transisi",
    state: "solid",
    group: 9,
    period: 4,
    block: "d",
    shells: [2, 8, 15, 2],
    config: "[Ar] 3d⁷ 4s²",
    electronegativity: 1.88,
    meltingPoint: 1495,
    boilingPoint: 2927,
    density: 8.90,
    discovered: 1735,
    discoverer: "Georg Brandt",
    summary: "Kobalt digunakan dalam katoda baterai lithium-ion modern untuk kendaraan listrik dan gadget, serta memberikan pigmen biru pada keramik."
  },
  {
    number: 28,
    symbol: "Ni",
    name: "Nikel",
    latinName: "Niccolum",
    mass: 58.693,
    category: "transition-metal",
    categoryName: "Logam Transisi",
    state: "solid",
    group: 10,
    period: 4,
    block: "d",
    shells: [2, 8, 16, 2],
    config: "[Ar] 3d⁸ 4s²",
    electronegativity: 1.91,
    meltingPoint: 1455,
    boilingPoint: 2913,
    density: 8.908,
    discovered: 1751,
    discoverer: "Axel Fredrik Cronstedt",
    summary: "Nikel adalah logam perak keras yang tahan korosi. Indonesia memiliki cadangan bijih nikel terbesar di dunia yang krusial untuk industri baterai."
  },
  {
    number: 29,
    symbol: "Cu",
    name: "Tembaga",
    latinName: "Cuprum",
    mass: 63.546,
    category: "transition-metal",
    categoryName: "Logam Transisi",
    state: "solid",
    group: 11,
    period: 4,
    block: "d",
    shells: [2, 8, 18, 1],
    config: "[Ar] 3d¹⁰ 4s¹",
    electronegativity: 1.90,
    meltingPoint: 1084.62,
    boilingPoint: 2562,
    density: 8.96,
    discovered: "Kuno",
    discoverer: "Tidak diketahui",
    summary: "Tembaga dikenal sebagai konduktor listrik dan panas yang sangat efisien. Digunakan secara luas dalam kabel listrik dan perpipaan."
  },
  {
    number: 30,
    symbol: "Zn",
    name: "Seng",
    latinName: "Zincum",
    mass: 65.38,
    category: "transition-metal",
    categoryName: "Logam Transisi",
    state: "solid",
    group: 12,
    period: 4,
    block: "d",
    shells: [2, 8, 18, 2],
    config: "[Ar] 3d¹⁰ 4s²",
    electronegativity: 1.65,
    meltingPoint: 419.53,
    boilingPoint: 907,
    density: 7.14,
    discovered: 1746,
    discoverer: "Andreas Sigismund Marggraf",
    summary: "Seng digunakan dalam proses galvanisasi untuk melapisi besi dan baja agar tidak mudah berkarat."
  },
  {
    number: 31,
    symbol: "Ga",
    name: "Galium",
    latinName: "Gallium",
    mass: 69.723,
    category: "post-transition",
    categoryName: "Pasca-Transisi",
    state: "solid",
    group: 13,
    period: 4,
    block: "p",
    shells: [2, 8, 18, 3],
    config: "[Ar] 3d¹⁰ 4s² 4p¹",
    electronegativity: 1.81,
    meltingPoint: 29.76,
    boilingPoint: 2204,
    density: 5.91,
    discovered: 1875,
    discoverer: "Émile Lecoq de Boisbaudran",
    summary: "Galium memiliki titik lebur sangat rendah (29.76°C) sehingga dapat meleleh hanya dengan digenggam di telapak tangan manusia!"
  },
  {
    number: 32,
    symbol: "Ge",
    name: "Jermanium",
    latinName: "Germanium",
    mass: 72.630,
    category: "metalloid",
    categoryName: "Metaloid",
    state: "solid",
    group: 14,
    period: 4,
    block: "p",
    shells: [2, 8, 18, 4],
    config: "[Ar] 3d¹⁰ 4s² 4p²",
    electronegativity: 2.01,
    meltingPoint: 938.25,
    boilingPoint: 2833,
    density: 5.323,
    discovered: 1886,
    discoverer: "Clemens Winkler",
    summary: "Jermanium adalah metaloid semikonduktor penting yang digunakan dalam optik inframerah dan transistor generasi awal."
  },
  {
    number: 33,
    symbol: "As",
    name: "Arsenik",
    latinName: "Arsenicum",
    mass: 74.922,
    category: "metalloid",
    categoryName: "Metaloid",
    state: "solid",
    group: 15,
    period: 4,
    block: "p",
    shells: [2, 8, 18, 5],
    config: "[Ar] 3d¹⁰ 4s² 4p³",
    electronegativity: 2.18,
    meltingPoint: 817,
    boilingPoint: 614,
    density: 5.727,
    discovered: 1250,
    discoverer: "Albertus Magnus",
    summary: "Arsenik terkenal dalam sejarah sebagai racun yang mematikan. Namun juga memiliki kegunaan dalam pembuat semikonduktor Gallium Arsenide (GaAs)."
  },
  {
    number: 34,
    symbol: "Se",
    name: "Selenium",
    latinName: "Selenium",
    mass: 78.971,
    category: "nonmetal",
    categoryName: "Non-logam",
    state: "solid",
    group: 16,
    period: 4,
    block: "p",
    shells: [2, 8, 18, 6],
    config: "[Ar] 3d¹⁰ 4s² 4p⁴",
    electronegativity: 2.55,
    meltingPoint: 221,
    boilingPoint: 685,
    density: 4.81,
    discovered: 1817,
    discoverer: "Jöns Jacob Berzelius",
    summary: "Selenium memiliki sifat fotokonduktif di mana konduktivitas listriknya meningkat saat terkena cahaya. Digunakan pada sel fotovoltaik dan fotokopi."
  },
  {
    number: 35,
    symbol: "Br",
    name: "Bromin",
    latinName: "Bromum",
    mass: 79.904,
    category: "halogen",
    categoryName: "Halogen",
    state: "liquid",
    group: 17,
    period: 4,
    block: "p",
    shells: [2, 8, 18, 7],
    config: "[Ar] 3d¹⁰ 4s² 4p⁵",
    electronegativity: 2.96,
    meltingPoint: -7.2,
    boilingPoint: 58.8,
    density: 3.1028,
    discovered: 1826,
    discoverer: "Antoine Jérôme Balard",
    summary: "Bromin adalah satu-satunya unsur non-logam yang berwujud cair pada suhu ruang. Berwarna merah-cokelat dan mengeluarkan uap berbau tajam."
  },
  {
    number: 36,
    symbol: "Kr",
    name: "Kripton",
    latinName: "Krypton",
    mass: 83.798,
    category: "noble-gas",
    categoryName: "Gas Mulia",
    state: "gas",
    group: 18,
    period: 4,
    block: "p",
    shells: [2, 8, 18, 8],
    config: "[Ar] 3d¹⁰ 4s² 4p⁶",
    electronegativity: 3.00,
    meltingPoint: -157.36,
    boilingPoint: -153.22,
    density: 0.003749,
    discovered: 1898,
    discoverer: "William Ramsay, Morris Travers",
    summary: "Kripton adalah gas mulia tidak berwarna yang dapat menghasilkan sinar putih cerah ketika dialiri listrik, dipakai pada lampu kilat fotografi."
  },
  {
    number: 37,
    symbol: "Rb",
    name: "Rubidium",
    latinName: "Rubidium",
    mass: 85.468,
    category: "alkali-metal",
    categoryName: "Logam Alkali",
    state: "solid",
    group: 1,
    period: 5,
    block: "s",
    shells: [2, 8, 18, 8, 1],
    config: "[Kr] 5s¹",
    electronegativity: 0.82,
    meltingPoint: 39.31,
    boilingPoint: 688,
    density: 1.532,
    discovered: 1861,
    discoverer: "Robert Bunsen, Gustav Kirchhoff",
    summary: "Rubidium adalah logam alkali yang sangat reaktif dan dapat terbakar secara spontan di udara. Memiliki warna nyala merah keunguan."
  },
  {
    number: 38,
    symbol: "Sr",
    name: "Stronsium",
    latinName: "Strontium",
    mass: 87.62,
    category: "alkaline-earth",
    categoryName: "Alkali Tanah",
    state: "solid",
    group: 2,
    period: 5,
    block: "s",
    shells: [2, 8, 18, 8, 2],
    config: "[Kr] 5s²",
    electronegativity: 0.95,
    meltingPoint: 777,
    boilingPoint: 1382,
    density: 2.64,
    discovered: 1790,
    discoverer: "Adair Crawford",
    summary: "Garam stronsium memberikan warna merah menyala yang indah pada kembang api dan suar darurat."
  },
  {
    number: 39,
    symbol: "Y",
    name: "Ytrium",
    latinName: "Yttrium",
    mass: 88.906,
    category: "transition-metal",
    categoryName: "Logam Transisi",
    state: "solid",
    group: 3,
    period: 5,
    block: "d",
    shells: [2, 8, 18, 9, 2],
    config: "[Kr] 4d¹ 5s²",
    electronegativity: 1.22,
    meltingPoint: 1526,
    boilingPoint: 3336,
    density: 4.472,
    discovered: 1794,
    discoverer: "Johan Gadolin",
    summary: "Ytrium digunakan dalam pembuat fosfor merah pada layar CRT lama, LED, serta superkonduktor suhu tinggi (YBCO)."
  },
  {
    number: 40,
    symbol: "Zr",
    name: "Zirkonium",
    latinName: "Zirconium",
    mass: 91.224,
    category: "transition-metal",
    categoryName: "Logam Transisi",
    state: "solid",
    group: 4,
    period: 5,
    block: "d",
    shells: [2, 8, 18, 10, 2],
    config: "[Kr] 4d² 5s²",
    electronegativity: 1.33,
    meltingPoint: 1855,
    boilingPoint: 4409,
    density: 6.52,
    discovered: 1789,
    discoverer: "Martin Heinrich Klaproth",
    summary: "Zirkonium sangat tahan korosi dan penyerapan neutron rendah, menjadikannya bahan utama pelapis bahan bakar reaktor nuklir."
  },
  {
    number: 41,
    symbol: "Nb",
    name: "Niobium",
    latinName: "Niobium",
    mass: 92.906,
    category: "transition-metal",
    categoryName: "Logam Transisi",
    state: "solid",
    group: 5,
    period: 5,
    block: "d",
    shells: [2, 8, 18, 12, 1],
    config: "[Kr] 4d⁴ 5s¹",
    electronegativity: 1.6,
    meltingPoint: 2477,
    boilingPoint: 4744,
    density: 8.57,
    discovered: 1801,
    discoverer: "Charles Hatchett",
    summary: "Niobium digunakan pada magnet superkonduktor pemindai MRI medis dan pemacu partikel."
  },
  {
    number: 42,
    symbol: "Mo",
    name: "Molibdenum",
    latinName: "Molybdenum",
    mass: 95.95,
    category: "transition-metal",
    categoryName: "Logam Transisi",
    state: "solid",
    group: 6,
    period: 5,
    block: "d",
    shells: [2, 8, 18, 13, 1],
    config: "[Kr] 4d⁵ 5s¹",
    electronegativity: 2.16,
    meltingPoint: 2623,
    boilingPoint: 4639,
    density: 10.28,
    discovered: 1778,
    discoverer: "Carl Wilhelm Scheele",
    summary: "Molibdenum memiliki titik lebur sangat tinggi dan kekerasan yang konsisten, sering dipakai dalam paduan baja tahan panas."
  },
  {
    number: 43,
    symbol: "Tc",
    name: "Teknesium",
    latinName: "Technetium",
    mass: 98,
    category: "transition-metal",
    categoryName: "Logam Transisi",
    state: "solid",
    group: 7,
    period: 5,
    block: "d",
    shells: [2, 8, 18, 13, 2],
    config: "[Kr] 4d⁵ 5s²",
    electronegativity: 1.9,
    meltingPoint: 2157,
    boilingPoint: 4265,
    density: 11,
    discovered: 1937,
    discoverer: "Emilio Segrè, Carlo Perrier",
    summary: "Teknesium adalah unsur buatan manusia pertama yang diproduksi secara sintetis. Isotop Tc-99m sangat populer dalam pemindaian medis kedokteran nuklir."
  },
  {
    number: 44,
    symbol: "Ru",
    name: "Rutenium",
    latinName: "Ruthenium",
    mass: 101.07,
    category: "transition-metal",
    categoryName: "Logam Transisi",
    state: "solid",
    group: 8,
    period: 5,
    block: "d",
    shells: [2, 8, 18, 15, 1],
    config: "[Kr] 4d⁷ 5s¹",
    electronegativity: 2.2,
    meltingPoint: 2334,
    boilingPoint: 4150,
    density: 12.45,
    discovered: 1844,
    discoverer: "Karl Ernst Claus",
    summary: "Rutenium adalah bagian dari kelompok logam platina. Berfungsi sebagai katalisator industri kimia dan pelapis kontak listrik."
  },
  {
    number: 45,
    symbol: "Rh",
    name: "Rodium",
    latinName: "Rhodium",
    mass: 102.91,
    category: "transition-metal",
    categoryName: "Logam Transisi",
    state: "solid",
    group: 9,
    period: 5,
    block: "d",
    shells: [2, 8, 18, 16, 1],
    config: "[Kr] 4d⁸ 5s¹",
    electronegativity: 2.28,
    meltingPoint: 1964,
    boilingPoint: 3695,
    density: 12.41,
    discovered: 1803,
    discoverer: "William Hyde Wollaston",
    summary: "Rodium adalah salah satu logam mulia paling langka dan berharga di dunia, komponen utama katalis konverter emisi mobil."
  },
  {
    number: 46,
    symbol: "Pd",
    name: "Paladium",
    latinName: "Palladium",
    mass: 106.42,
    category: "transition-metal",
    categoryName: "Logam Transisi",
    state: "solid",
    group: 10,
    period: 5,
    block: "d",
    shells: [2, 8, 18, 18],
    config: "[Kr] 4d¹⁰",
    electronegativity: 2.20,
    meltingPoint: 1554.9,
    boilingPoint: 2963,
    density: 12.023,
    discovered: 1803,
    discoverer: "William Hyde Wollaston",
    summary: "Paladium mampu menyerap gas hidrogen hingga 900 kali volumenya sendiri. Banyak dipakai dalam perhiasan emas putih dan industri otomotif."
  },
  {
    number: 47,
    symbol: "Ag",
    name: "Perak",
    latinName: "Argentum",
    mass: 107.87,
    category: "transition-metal",
    categoryName: "Logam Transisi",
    state: "solid",
    group: 11,
    period: 5,
    block: "d",
    shells: [2, 8, 18, 18, 1],
    config: "[Kr] 4d¹⁰ 5s¹",
    electronegativity: 1.93,
    meltingPoint: 961.78,
    boilingPoint: 2162,
    density: 10.49,
    discovered: "Kuno",
    discoverer: "Tidak diketahui",
    summary: "Perak memiliki konduktivitas listrik, konduktivitas termal, dan reflektivitas cahaya tertinggi di antara semua logam."
  },
  {
    number: 48,
    symbol: "Cd",
    name: "Kadmium",
    latinName: "Cadmium",
    mass: 112.41,
    category: "transition-metal",
    categoryName: "Logam Transisi",
    state: "solid",
    group: 12,
    period: 5,
    block: "d",
    shells: [2, 8, 18, 18, 2],
    config: "[Kr] 4d¹⁰ 5s²",
    electronegativity: 1.69,
    meltingPoint: 321.07,
    boilingPoint: 767,
    density: 8.65,
    discovered: 1817,
    discoverer: "Karl Samuel Leberecht Hermann, Friedrich Stromeyer",
    summary: "Kadmium adalah logam beracun yang digunakan pada baterai isi ulang NiCd tua dan pigmen cat cerah."
  },
  {
    number: 49,
    symbol: "In",
    name: "Indium",
    latinName: "Indium",
    mass: 114.82,
    category: "post-transition",
    categoryName: "Pasca-Transisi",
    state: "solid",
    group: 13,
    period: 5,
    block: "p",
    shells: [2, 8, 18, 18, 3],
    config: "[Kr] 4d¹⁰ 5s² 5p¹",
    electronegativity: 1.78,
    meltingPoint: 156.6,
    boilingPoint: 2072,
    density: 7.31,
    discovered: 1863,
    discoverer: "Ferdinand Reich, Hieronymous Theodor Richter",
    summary: "Indium Tin Oxide (ITO) adalah bahan konduktif transparan yang menjadi kunci layar sentuh (touchscreen) pada smartphone modern."
  },
  {
    number: 50,
    symbol: "Sn",
    name: "Timah",
    latinName: "Stannum",
    mass: 118.71,
    category: "post-transition",
    categoryName: "Pasca-Transisi",
    state: "solid",
    group: 14,
    period: 5,
    block: "p",
    shells: [2, 8, 18, 18, 4],
    config: "[Kr] 4d¹⁰ 5s² 5p²",
    electronegativity: 1.96,
    meltingPoint: 231.93,
    boilingPoint: 2602,
    density: 7.31,
    discovered: "Kuno",
    discoverer: "Tidak diketahui",
    summary: "Timah adalah logam lunak perak yang telah digunakan sejak zaman perunggu untuk campuran perunggu dan kabel solder elektronik."
  },
  {
    number: 51,
    symbol: "Sb",
    name: "Antimon",
    latinName: "Stibium",
    mass: 121.76,
    category: "metalloid",
    categoryName: "Metaloid",
    state: "solid",
    group: 15,
    period: 5,
    block: "p",
    shells: [2, 8, 18, 18, 5],
    config: "[Kr] 4d¹⁰ 5s² 5p³",
    electronegativity: 2.05,
    meltingPoint: 630.63,
    boilingPoint: 1587,
    density: 6.697,
    discovered: "Kuno",
    discoverer: "Tidak diketahui",
    summary: "Antimon adalah metaloid berkilau abu-abu yang ditambahkan pada bahan tahan api dan akumulator aki timbal."
  },
  {
    number: 52,
    symbol: "Te",
    name: "Telurium",
    latinName: "Tellurium",
    mass: 127.60,
    category: "metalloid",
    categoryName: "Metaloid",
    state: "solid",
    group: 16,
    period: 5,
    block: "p",
    shells: [2, 8, 18, 18, 6],
    config: "[Kr] 4d¹⁰ 5s² 5p⁴",
    electronegativity: 2.1,
    meltingPoint: 449.51,
    boilingPoint: 988,
    density: 6.24,
    discovered: 1782,
    discoverer: "Franz-Joseph Müller von Reichenstein",
    summary: "Telurium adalah metaloid langka yang digunakan pada sel surya kadmium telurida (CdTe) dan perangkat termoelektrik."
  },
  {
    number: 53,
    symbol: "I",
    name: "Yodium",
    latinName: "Iodum",
    mass: 126.90,
    category: "halogen",
    categoryName: "Halogen",
    state: "solid",
    group: 17,
    period: 5,
    block: "p",
    shells: [2, 8, 18, 18, 7],
    config: "[Kr] 4d¹⁰ 5s² 5p⁵",
    electronegativity: 2.66,
    meltingPoint: 113.7,
    boilingPoint: 184.3,
    density: 4.933,
    discovered: 1811,
    discoverer: "Bernard Courtois",
    summary: "Yodium adalah halogen berwujud padat keunguan yang menyublim menjadi uap ungu. Sangat penting bagi fungsi kelenjar tiroid manusia."
  },
  {
    number: 54,
    symbol: "Xe",
    name: "Xenon",
    latinName: "Xenon",
    mass: 131.29,
    category: "noble-gas",
    categoryName: "Gas Mulia",
    state: "gas",
    group: 18,
    period: 5,
    block: "p",
    shells: [2, 8, 18, 18, 8],
    config: "[Kr] 4d¹⁰ 5s² 5p⁶",
    electronegativity: 2.6,
    meltingPoint: -111.75,
    boilingPoint: -108.099,
    density: 0.005894,
    discovered: 1898,
    discoverer: "William Ramsay, Morris Travers",
    summary: "Xenon adalah gas mulia berat yang memancarkan kilau biru kebiruan. Digunakan pada pendorong ion satelit luar angkasa."
  },
  {
    number: 55,
    symbol: "Cs",
    name: "Sesium",
    latinName: "Caesium",
    mass: 132.91,
    category: "alkali-metal",
    categoryName: "Logam Alkali",
    state: "solid",
    group: 1,
    period: 6,
    block: "s",
    shells: [2, 8, 18, 18, 8, 1],
    config: "[Xe] 6s¹",
    electronegativity: 0.79,
    meltingPoint: 28.5,
    boilingPoint: 671,
    density: 1.93,
    discovered: 1860,
    discoverer: "Robert Bunsen, Gustav Kirchhoff",
    summary: "Sesium adalah logam cair keemasan di dekat suhu ruang. Digunakan pada Jam Atom Sesium yang mendefinisikan standar detik internasional secara presisi."
  },
  {
    number: 56,
    symbol: "Ba",
    name: "Barium",
    latinName: "Barium",
    mass: 137.33,
    category: "alkaline-earth",
    categoryName: "Alkali Tanah",
    state: "solid",
    group: 2,
    period: 6,
    block: "s",
    shells: [2, 8, 18, 18, 8, 2],
    config: "[Xe] 6s²",
    electronegativity: 0.89,
    meltingPoint: 727,
    boilingPoint: 1897,
    density: 3.51,
    discovered: 1808,
    discoverer: "Humphry Davy",
    summary: "Senyawa Barium Sulfat digunakan dalam prosedur medis pencitraan sinar-X sistem pencernaan sebagai agen kontras."
  },
  {
    number: 57,
    symbol: "La",
    name: "Lantanum",
    latinName: "Lanthanum",
    mass: 138.91,
    category: "lanthanide",
    categoryName: "Lantanida",
    state: "solid",
    group: 3,
    period: 6,
    block: "f",
    shells: [2, 8, 18, 18, 9, 2],
    config: "[Xe] 5d¹ 6s²",
    electronegativity: 1.10,
    meltingPoint: 920,
    boilingPoint: 3464,
    density: 6.162,
    discovered: 1839,
    discoverer: "Carl Gustaf Mosander",
    summary: "Lantanum adalah unsur pertama dari deret Lantanida. Digunakan dalam lensa kamera kualitas tinggi dan elektroda lampu busur."
  },
  {
    number: 58,
    symbol: "Ce",
    name: "Serium",
    latinName: "Cerium",
    mass: 140.12,
    category: "lanthanide",
    categoryName: "Lantanida",
    state: "solid",
    group: 3,
    period: 6,
    block: "f",
    shells: [2, 8, 18, 19, 9, 2],
    config: "[Xe] 4f¹ 5d¹ 6s²",
    electronegativity: 1.12,
    meltingPoint: 795,
    boilingPoint: 3443,
    density: 6.77,
    discovered: 1803,
    discoverer: "Martin Heinrich Klaproth, Jöns Jacob Berzelius",
    summary: "Serium adalah logam lantanida paling melimpah. Digunakan pada batu pemantik korek api dan sebagai agen pemoles kaca."
  },
  {
    number: 59,
    symbol: "Pr",
    name: "Praseodimium",
    latinName: "Praseodymium",
    mass: 140.91,
    category: "lanthanide",
    categoryName: "Lantanida",
    state: "solid",
    group: 3,
    period: 6,
    block: "f",
    shells: [2, 8, 18, 21, 8, 2],
    config: "[Xe] 4f³ 6s²",
    electronegativity: 1.13,
    meltingPoint: 931,
    boilingPoint: 3520,
    density: 6.77,
    discovered: 1885,
    discoverer: "Carl Auer von Welsbach",
    summary: "Praseodimium memberikan warna hijau kekuningan pada kaca dan digunakan dalam paduan magnet Neodimium super kuat."
  },
  {
    number: 60,
    symbol: "Nd",
    name: "Neodimium",
    latinName: "Neodymium",
    mass: 144.24,
    category: "lanthanide",
    categoryName: "Lantanida",
    state: "solid",
    group: 3,
    period: 6,
    block: "f",
    shells: [2, 8, 18, 22, 8, 2],
    config: "[Xe] 4f⁴ 6s²",
    electronegativity: 1.14,
    meltingPoint: 1024,
    boilingPoint: 3074,
    density: 7.01,
    discovered: 1885,
    discoverer: "Carl Auer von Welsbach",
    summary: "Neodimium digunakan untuk membuat magnet permanen terkuat yang dikenal manusia (Magnet NdFeB) pada speaker, earphone, dan motor listrik."
  },
  {
    number: 61,
    symbol: "Pm",
    name: "Prometium",
    latinName: "Promethium",
    mass: 145,
    category: "lanthanide",
    categoryName: "Lantanida",
    state: "solid",
    group: 3,
    period: 6,
    block: "f",
    shells: [2, 8, 18, 23, 8, 2],
    config: "[Xe] 4f⁵ 6s²",
    electronegativity: 1.13,
    meltingPoint: 1042,
    boilingPoint: 3000,
    density: 7.26,
    discovered: 1945,
    discoverer: "Jacob A. Marinsky, Lawrence E. Glendenin, Charles D. Coryell",
    summary: "Prometium adalah satu-satunya lantanida yang bersifat radioaktif alami. Digunakan dalam baterai atom berbasis peluruhan beta."
  },
  {
    number: 62,
    symbol: "Sm",
    name: "Samarium",
    latinName: "Samarium",
    mass: 150.36,
    category: "lanthanide",
    categoryName: "Lantanida",
    state: "solid",
    group: 3,
    period: 6,
    block: "f",
    shells: [2, 8, 18, 25, 8, 2],
    config: "[Xe] 4f⁶ 6s²",
    electronegativity: 1.17,
    meltingPoint: 1072,
    boilingPoint: 1794,
    density: 7.52,
    discovered: 1879,
    discoverer: "Paul-Émile Lecoq de Boisbaudran",
    summary: "Samarium digunakan dalam pembuat magnet samarium-kobalt yang tahan terhadap suhu ekstrem tinggi tanpa kehilangan daya magnet."
  },
  {
    number: 63,
    symbol: "Eu",
    name: "Europium",
    latinName: "Europium",
    mass: 151.96,
    category: "lanthanide",
    categoryName: "Lantanida",
    state: "solid",
    group: 3,
    period: 6,
    block: "f",
    shells: [2, 8, 18, 25, 9, 2],
    config: "[Xe] 4f⁷ 6s²",
    electronegativity: 1.2,
    meltingPoint: 822,
    boilingPoint: 1529,
    density: 5.244,
    discovered: 1901,
    discoverer: "Eugène-Anatole Demarçay",
    summary: "Europium adalah unsur lantanida yang sangat fosforesens, digunakan pada tinta anti-pemalsuan uang kertas Euro."
  },
  {
    number: 64,
    symbol: "Gd",
    name: "Gadolinium",
    latinName: "Gadolinium",
    mass: 157.25,
    category: "lanthanide",
    categoryName: "Lantanida",
    state: "solid",
    group: 3,
    period: 6,
    block: "f",
    shells: [2, 8, 18, 25, 9, 2],
    config: "[Xe] 4f⁷ 5d¹ 6s²",
    electronegativity: 1.2,
    meltingPoint: 1313,
    boilingPoint: 3273,
    density: 7.90,
    discovered: 1880,
    discoverer: "Jean Charles Galissard de Marignac",
    summary: "Gadolinium memiliki sifat paramagnetik unik yang menjadikannya zat kontras utama pada pemindaian MRI."
  },
  {
    number: 65,
    symbol: "Tb",
    name: "Terbium",
    latinName: "Terbium",
    mass: 158.93,
    category: "lanthanide",
    categoryName: "Lantanida",
    state: "solid",
    group: 3,
    period: 6,
    block: "f",
    shells: [2, 8, 18, 27, 8, 2],
    config: "[Xe] 4f⁹ 6s²",
    electronegativity: 1.2,
    meltingPoint: 1356,
    boilingPoint: 3230,
    density: 8.23,
    discovered: 1843,
    discoverer: "Carl Gustaf Mosander",
    summary: "Terbium digunakan pada fosfor hijau dalam layar OLED dan lampu fluoresen efisiensi tinggi."
  },
  {
    number: 66,
    symbol: "Dy",
    name: "Disprosium",
    latinName: "Dysprosium",
    mass: 162.50,
    category: "lanthanide",
    categoryName: "Lantanida",
    state: "solid",
    group: 3,
    period: 6,
    block: "f",
    shells: [2, 8, 18, 28, 8, 2],
    config: "[Xe] 4f¹⁰ 6s²",
    electronegativity: 1.22,
    meltingPoint: 1412,
    boilingPoint: 2567,
    density: 8.55,
    discovered: 1886,
    discoverer: "Paul-Émile Lecoq de Boisbaudran",
    summary: "Disprosium ditambahkan pada magnet permanen mobil listrik agar magnet tidak mendemagnetisasi pada temperatur tinggi."
  },
  {
    number: 67,
    symbol: "Ho",
    name: "Holmium",
    latinName: "Holmium",
    mass: 164.93,
    category: "lanthanide",
    categoryName: "Lantanida",
    state: "solid",
    group: 3,
    period: 6,
    block: "f",
    shells: [2, 8, 18, 29, 8, 2],
    config: "[Xe] 4f¹¹ 6s²",
    electronegativity: 1.23,
    meltingPoint: 1474,
    boilingPoint: 2700,
    density: 8.79,
    discovered: 1878,
    discoverer: "Marc Delafontaine, Jacques-Louis Soret",
    summary: "Holmium memiliki momen magnetik alami tertinggi di antara semua unsur alami."
  },
  {
    number: 68,
    symbol: "Er",
    name: "Erbium",
    latinName: "Erbium",
    mass: 167.26,
    category: "lanthanide",
    categoryName: "Lantanida",
    state: "solid",
    group: 3,
    period: 6,
    block: "f",
    shells: [2, 8, 18, 30, 8, 2],
    config: "[Xe] 4f¹² 6s²",
    electronegativity: 1.24,
    meltingPoint: 1529,
    boilingPoint: 2868,
    density: 9.066,
    discovered: 1843,
    discoverer: "Carl Gustaf Mosander",
    summary: "Erbium digunakan sebagai penguat sinyal pada kabel serat optik transmisi data internet jarak jauh (EDFA)."
  },
  {
    number: 69,
    symbol: "Tm",
    name: "Tulium",
    latinName: "Thulium",
    mass: 168.93,
    category: "lanthanide",
    categoryName: "Lantanida",
    state: "solid",
    group: 3,
    period: 6,
    block: "f",
    shells: [2, 8, 18, 31, 8, 2],
    config: "[Xe] 4f¹³ 6s²",
    electronegativity: 1.25,
    meltingPoint: 1545,
    boilingPoint: 1950,
    density: 9.32,
    discovered: 1879,
    discoverer: "Per Teodor Cleve",
    summary: "Tulium adalah lantanida paling langka kedua. Digunakan sebagai sumber radiasi portabel pada mesin Sinar-X lapangan."
  },
  {
    number: 70,
    symbol: "Yb",
    name: "Yterbium",
    latinName: "Ytterbium",
    mass: 173.05,
    category: "lanthanide",
    categoryName: "Lantanida",
    state: "solid",
    group: 3,
    period: 6,
    block: "f",
    shells: [2, 8, 18, 32, 8, 2],
    config: "[Xe] 4f¹⁴ 6s²",
    electronegativity: 1.1,
    meltingPoint: 824,
    boilingPoint: 1196,
    density: 6.90,
    discovered: 1878,
    discoverer: "Jean Charles Galissard de Marignac",
    summary: "Yterbium dipakai pada jam atom laser presisi ultra-tinggi dan pemuat serat optik laser pemotong industri."
  },
  {
    number: 71,
    symbol: "Lu",
    name: "Lutetium",
    latinName: "Lutetium",
    mass: 174.97,
    category: "lanthanide",
    categoryName: "Lantanida",
    state: "solid",
    group: 3,
    period: 6,
    block: "d",
    shells: [2, 8, 18, 32, 9, 2],
    config: "[Xe] 4f¹⁴ 5d¹ 6s²",
    electronegativity: 1.27,
    meltingPoint: 1663,
    boilingPoint: 3402,
    density: 9.841,
    discovered: 1907,
    discoverer: "Georges Urbain, Carl Auer von Welsbach",
    summary: "Lutetium adalah unsur lantanida paling keras dan paling padat. Digunakan dalam detektor pemindaian PET-Scan rumah sakit."
  },
  {
    number: 72,
    symbol: "Hf",
    name: "Hafnium",
    latinName: "Hafnium",
    mass: 178.49,
    category: "transition-metal",
    categoryName: "Logam Transisi",
    state: "solid",
    group: 4,
    period: 6,
    block: "d",
    shells: [2, 8, 18, 32, 10, 2],
    config: "[Xe] 4f¹⁴ 5d² 6s²",
    electronegativity: 1.3,
    meltingPoint: 2233,
    boilingPoint: 4603,
    density: 13.31,
    discovered: 1923,
    discoverer: "Dirk Coster, George de Hevesy",
    summary: "Hafnium sangat efektif menyerap neutron, digunakan pada batang kendali reaktor nuklir kapal selam."
  },
  {
    number: 73,
    symbol: "Ta",
    name: "Tantalum",
    latinName: "Tantalum",
    mass: 180.95,
    category: "transition-metal",
    categoryName: "Logam Transisi",
    state: "solid",
    group: 5,
    period: 6,
    block: "d",
    shells: [2, 8, 18, 32, 11, 2],
    config: "[Xe] 4f¹⁴ 5d³ 6s²",
    electronegativity: 1.5,
    meltingPoint: 3017,
    boilingPoint: 5458,
    density: 16.69,
    discovered: 1802,
    discoverer: "Anders Gustaf Ekeberg",
    summary: "Tantalum digunakan dalam pembuatan kapasitor mikro ukuran miniatur pada papan sirkuit smartphone dan elektronik."
  },
  {
    number: 74,
    symbol: "W",
    name: "Wolfram",
    latinName: "Tungsten",
    mass: 183.84,
    category: "transition-metal",
    categoryName: "Logam Transisi",
    state: "solid",
    group: 6,
    period: 6,
    block: "d",
    shells: [2, 8, 18, 32, 12, 2],
    config: "[Xe] 4f¹⁴ 5d⁴ 6s²",
    electronegativity: 2.36,
    meltingPoint: 3422,
    boilingPoint: 5555,
    density: 19.25,
    discovered: 1783,
    discoverer: "Juan José Elhuyar, Fausto Elhuyar",
    summary: "Wolfram (Tungsten) memiliki titik lebur tertinggi dari seluruh unsur logam murni (3422°C), dahulu populer sebagai filamen lampu pijar."
  },
  {
    number: 75,
    symbol: "Re",
    name: "Renium",
    latinName: "Rhenium",
    mass: 186.21,
    category: "transition-metal",
    categoryName: "Logam Transisi",
    state: "solid",
    group: 7,
    period: 6,
    block: "d",
    shells: [2, 8, 18, 32, 13, 2],
    config: "[Xe] 4f¹⁴ 5d⁵ 6s²",
    electronegativity: 1.9,
    meltingPoint: 3186,
    boilingPoint: 5596,
    density: 21.02,
    discovered: 1925,
    discoverer: "Masataka Ogawa, Walter Noddack, Ida Tacke",
    summary: "Renium adalah salah satu logam paling langka di kerak bumi. Digunakan dalam paduan super mesin jet pesawat."
  },
  {
    number: 76,
    symbol: "Os",
    name: "Osmium",
    latinName: "Osmium",
    mass: 190.23,
    category: "transition-metal",
    categoryName: "Logam Transisi",
    state: "solid",
    group: 8,
    period: 6,
    block: "d",
    shells: [2, 8, 18, 32, 14, 2],
    config: "[Xe] 4f¹⁴ 5d⁶ 6s²",
    electronegativity: 2.2,
    meltingPoint: 3033,
    boilingPoint: 5012,
    density: 22.59,
    discovered: 1803,
    discoverer: "Smithson Tennant",
    summary: "Osmium adalah zat/unsur alami paling padat di Bumi (massa jenis 22.59 g/cm³), sekitar dua kali lebih padat dari timbal."
  },
  {
    number: 77,
    symbol: "Ir",
    name: "Iridium",
    latinName: "Iridium",
    mass: 192.22,
    category: "transition-metal",
    categoryName: "Logam Transisi",
    state: "solid",
    group: 9,
    period: 6,
    block: "d",
    shells: [2, 8, 18, 32, 15, 2],
    config: "[Xe] 4f¹⁴ 5d⁷ 6s²",
    electronegativity: 2.2,
    meltingPoint: 2446,
    boilingPoint: 4428,
    density: 22.56,
    discovered: 1803,
    discoverer: "Smithson Tennant",
    summary: "Iridium sangat tahan korosi dan memiliki konsentrasi tinggi pada lapisan geologi batas K-T penyabab kepunahan dinosaurus."
  },
  {
    number: 78,
    symbol: "Pt",
    name: "Platina",
    latinName: "Platinum",
    mass: 195.08,
    category: "transition-metal",
    categoryName: "Logam Transisi",
    state: "solid",
    group: 10,
    period: 6,
    block: "d",
    shells: [2, 8, 18, 32, 17, 1],
    config: "[Xe] 4f¹⁴ 5d⁹ 6s¹",
    electronegativity: 2.28,
    meltingPoint: 1768.3,
    boilingPoint: 3825,
    density: 21.45,
    discovered: 1735,
    discoverer: "Antonio de Ulloa",
    summary: "Platina adalah logam mulia yang tidak mudah teroksidasi. Digunakan sebagai perhiasan mewah, peralat medis, dan katalisator."
  },
  {
    number: 79,
    symbol: "Au",
    name: "Emas",
    latinName: "Aurum",
    mass: 196.97,
    category: "transition-metal",
    categoryName: "Logam Transisi",
    state: "solid",
    group: 11,
    period: 6,
    block: "d",
    shells: [2, 8, 18, 32, 18, 1],
    config: "[Xe] 4f¹⁴ 5d¹⁰ 6s¹",
    electronegativity: 2.54,
    meltingPoint: 1064.18,
    boilingPoint: 2856,
    density: 19.30,
    discovered: "Kuno",
    discoverer: "Tidak diketahui",
    summary: "Emas adalah logam mulia bernilai tinggi sejak zaman purba karena kilau kuningnya yang tak bisa pudar dan sifatnya yang mudah ditempa."
  },
  {
    number: 80,
    symbol: "Hg",
    name: "Raksa",
    latinName: "Hydrargyrum",
    mass: 200.59,
    category: "transition-metal",
    categoryName: "Logam Transisi",
    state: "liquid",
    group: 12,
    period: 6,
    block: "d",
    shells: [2, 8, 18, 32, 18, 2],
    config: "[Xe] 4f¹⁴ 5d¹⁰ 6s²",
    electronegativity: 2.00,
    meltingPoint: -38.83,
    boilingPoint: 356.73,
    density: 13.534,
    discovered: "Kuno",
    discoverer: "Tidak diketahui",
    summary: "Raksa (Mercury) adalah satu-satunya logam yang wujudnya cair pada suhu dan tekanan standar. Dahulu dipakai pada termometer."
  },
  {
    number: 81,
    symbol: "Tl",
    name: "Talium",
    latinName: "Thallium",
    mass: 204.38,
    category: "post-transition",
    categoryName: "Pasca-Transisi",
    state: "solid",
    group: 13,
    period: 6,
    block: "p",
    shells: [2, 8, 18, 32, 18, 3],
    config: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p¹",
    electronegativity: 1.62,
    meltingPoint: 304,
    boilingPoint: 1473,
    density: 11.85,
    discovered: 1861,
    discoverer: "William Crookes",
    summary: "Talium adalah logam beracun tinggi tanpa rasa maupun bau. Pernah digunakan sebagai racun tikus sebelum dilarang."
  },
  {
    number: 82,
    symbol: "Pb",
    name: "Timbal",
    latinName: "Plumbum",
    mass: 207.2,
    category: "post-transition",
    categoryName: "Pasca-Transisi",
    state: "solid",
    group: 14,
    period: 6,
    block: "p",
    shells: [2, 8, 18, 32, 18, 4],
    config: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p²",
    electronegativity: 1.87,
    meltingPoint: 327.46,
    boilingPoint: 1749,
    density: 11.34,
    discovered: "Kuno",
    discoverer: "Tidak diketahui",
    summary: "Timbal adalah logam berat yang sangat padat namun lunak. Digunakan sebagai perisai radiasi Sinar-X dan aki kendaraan."
  },
  {
    number: 83,
    symbol: "Bi",
    name: "Bismut",
    latinName: "Bismuthum",
    mass: 208.98,
    category: "post-transition",
    categoryName: "Pasca-Transisi",
    state: "solid",
    group: 15,
    period: 6,
    block: "p",
    shells: [2, 8, 18, 32, 18, 5],
    config: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p³",
    electronegativity: 2.02,
    meltingPoint: 271.4,
    boilingPoint: 1564,
    density: 9.78,
    discovered: 1753,
    discoverer: "Claude François Geoffroy",
    summary: "Bismut memiliki kristal teroksidasi berliku-liku dengan warna-warni pelangi alami yang indah. Tidak beracun dibanding timbal."
  },
  {
    number: 84,
    symbol: "Po",
    name: "Polonium",
    latinName: "Polonium",
    mass: 209,
    category: "post-transition",
    categoryName: "Pasca-Transisi",
    state: "solid",
    group: 16,
    period: 6,
    block: "p",
    shells: [2, 8, 18, 32, 18, 6],
    config: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁴",
    electronegativity: 2.0,
    meltingPoint: 254,
    boilingPoint: 962,
    density: 9.196,
    discovered: 1898,
    discoverer: "Marie Curie, Pierre Curie",
    summary: "Polonium adalah unsur radioaktif langka yang memancarkan partikel alfa intensif, dinamai dari tanah kelahiran Marie Curie (Polandia)."
  },
  {
    number: 85,
    symbol: "At",
    name: "Astatin",
    latinName: "Astatum",
    mass: 210,
    category: "halogen",
    categoryName: "Halogen",
    state: "solid",
    group: 17,
    period: 6,
    block: "p",
    shells: [2, 8, 18, 32, 18, 7],
    config: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁵",
    electronegativity: 2.2,
    meltingPoint: 302,
    boilingPoint: 337,
    density: 7,
    discovered: 1940,
    discoverer: "Dale R. Corson, Kenneth Ross MacKenzie, Emilio Segrè",
    summary: "Astatin adalah unsur alami paling langka di kerak bumi (diperkirakan kurang dari 30 gram di seluruh planet pada satu waktu)."
  },
  {
    number: 86,
    symbol: "Rn",
    name: "Radon",
    latinName: "Radon",
    mass: 222,
    category: "noble-gas",
    categoryName: "Gas Mulia",
    state: "gas",
    group: 18,
    period: 6,
    block: "p",
    shells: [2, 8, 18, 32, 18, 8],
    config: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁶",
    electronegativity: 2.2,
    meltingPoint: -71,
    boilingPoint: -61.7,
    density: 0.00973,
    discovered: 1900,
    discoverer: "Friedrich Ernst Dorn",
    summary: "Radon adalah gas mulia radioaktif tak berwarna yang dihasilkan dari peluruhan radium alami di tanah dan bebatuan."
  },
  {
    number: 87,
    symbol: "Fr",
    name: "Fransium",
    latinName: "Francium",
    mass: 223,
    category: "alkali-metal",
    categoryName: "Logam Alkali",
    state: "solid",
    group: 1,
    period: 7,
    block: "s",
    shells: [2, 8, 18, 32, 18, 8, 1],
    config: "[Rn] 7s¹",
    electronegativity: 0.79,
    meltingPoint: 27,
    boilingPoint: 677,
    density: 1.87,
    discovered: 1939,
    discoverer: "Marguerite Perey",
    summary: "Fransium adalah logam alkali yang sangat tidak stabil dan radioaktif, memiliki waktu paruh isotop paling stabil hanya 22 menit."
  },
  {
    number: 88,
    symbol: "Ra",
    name: "Radium",
    latinName: "Radium",
    mass: 226,
    category: "alkaline-earth",
    categoryName: "Alkali Tanah",
    state: "solid",
    group: 2,
    period: 7,
    block: "s",
    shells: [2, 8, 18, 32, 18, 8, 2],
    config: "[Rn] 7s²",
    electronegativity: 0.9,
    meltingPoint: 700,
    boilingPoint: 1737,
    density: 5.5,
    discovered: 1898,
    discoverer: "Marie Curie, Pierre Curie",
    summary: "Radium menyala biru kehijauan di kegelapan akibat sifat luminesensi radioaktifnya. Dahulu dipakai pada cat jarum jam malam."
  },
  {
    number: 89,
    symbol: "Ac",
    name: "Aktinium",
    latinName: "Actinium",
    mass: 227,
    category: "actinide",
    categoryName: "Aktinida",
    state: "solid",
    group: 3,
    period: 7,
    block: "f",
    shells: [2, 8, 18, 32, 18, 9, 2],
    config: "[Rn] 6d¹ 7s²",
    electronegativity: 1.1,
    meltingPoint: 1050,
    boilingPoint: 3198,
    density: 10.07,
    discovered: 1899,
    discoverer: "André-Louis Debierne",
    summary: "Aktinium adalah unsur awal dari deret Aktinida. Memancarkan cahaya biru intens di ruang gelap akibat intensitas radioaktivitasnya."
  },
  {
    number: 90,
    symbol: "Th",
    name: "Torium",
    latinName: "Thorium",
    mass: 232.04,
    category: "actinide",
    categoryName: "Aktinida",
    state: "solid",
    group: 3,
    period: 7,
    block: "f",
    shells: [2, 8, 18, 32, 18, 10, 2],
    config: "[Rn] 6d² 7s²",
    electronegativity: 1.3,
    meltingPoint: 1750,
    boilingPoint: 4788,
    density: 11.72,
    discovered: 1829,
    discoverer: "Jöns Jacob Berzelius",
    summary: "Torium adalah logam aktinida yang melimpah dan berpotensi menjadi bahan bakar reaktor nuklir generasi masa depan yang lebih aman."
  },
  {
    number: 91,
    symbol: "Pa",
    name: "Protaktinium",
    latinName: "Protactinium",
    mass: 231.04,
    category: "actinide",
    categoryName: "Aktinida",
    state: "solid",
    group: 3,
    period: 7,
    block: "f",
    shells: [2, 8, 18, 32, 20, 9, 2],
    config: "[Rn] 5f² 6d¹ 7s²",
    electronegativity: 1.5,
    meltingPoint: 1568,
    boilingPoint: 4027,
    density: 15.37,
    discovered: 1913,
    discoverer: "Oswald Helmuth Göhring, Kasimir Fajans",
    summary: "Protaktinium adalah unsur langka, mahal, dan sangat beracun radioaktif yang terbentuk dari peluruhan uranium."
  },
  {
    number: 92,
    symbol: "U",
    name: "Uranium",
    latinName: "Uranium",
    mass: 238.03,
    category: "actinide",
    categoryName: "Aktinida",
    state: "solid",
    group: 3,
    period: 7,
    block: "f",
    shells: [2, 8, 18, 32, 21, 9, 2],
    config: "[Rn] 5f³ 6d¹ 7s²",
    electronegativity: 1.38,
    meltingPoint: 1135,
    boilingPoint: 4131,
    density: 19.1,
    discovered: 1789,
    discoverer: "Martin Heinrich Klaproth",
    summary: "Uranium adalah unsur alami paling berat yang digunakan sebagai bahan bakar utama pembangkit listrik tenaga nuklir."
  },
  {
    number: 93,
    symbol: "Np",
    name: "Neptunium",
    latinName: "Neptunium",
    mass: 237,
    category: "actinide",
    categoryName: "Aktinida",
    state: "solid",
    group: 3,
    period: 7,
    block: "f",
    shells: [2, 8, 18, 32, 22, 9, 2],
    config: "[Rn] 5f⁴ 6d¹ 7s²",
    electronegativity: 1.36,
    meltingPoint: 639,
    boilingPoint: 4174,
    density: 20.45,
    discovered: 1940,
    discoverer: "Edwin McMillan, Philip H. Abelson",
    summary: "Neptunium adalah unsur transuranium sintetik pertama yang dibuat dengan menembakkan neutron pada uranium."
  },
  {
    number: 94,
    symbol: "Pu",
    name: "Plutonium",
    latinName: "Plutonium",
    mass: 244,
    category: "actinide",
    categoryName: "Aktinida",
    state: "solid",
    group: 3,
    period: 7,
    block: "f",
    shells: [2, 8, 18, 32, 24, 8, 2],
    config: "[Rn] 5f⁶ 7s²",
    electronegativity: 1.28,
    meltingPoint: 639.4,
    boilingPoint: 3228,
    density: 19.816,
    discovered: 1940,
    discoverer: "Glenn T. Seaborg, Edwin McMillan, Joseph W. Kennedy, Arthur Wahl",
    summary: "Plutonium-239 adalah bahan fisil utama senjata nuklir dan pembangkit termoelektrik radioisotop pada wahana antariksa Voyager."
  },
  {
    number: 95,
    symbol: "Am",
    name: "Amerisium",
    latinName: "Americium",
    mass: 243,
    category: "actinide",
    categoryName: "Aktinida",
    state: "solid",
    group: 3,
    period: 7,
    block: "f",
    shells: [2, 8, 18, 32, 25, 8, 2],
    config: "[Rn] 5f⁷ 7s²",
    electronegativity: 1.13,
    meltingPoint: 1176,
    boilingPoint: 2607,
    density: 12,
    discovered: 1944,
    discoverer: "Glenn T. Seaborg, Ralph A. James, Leon O. Morgan, Albert Ghiorso",
    summary: "Amerisium-241 memancarkan partikel alfa dan digunakan secara komersial pada detektor asap ionisasi di dalam rumah."
  },
  {
    number: 96,
    symbol: "Cm",
    name: "Kurium",
    latinName: "Curium",
    mass: 247,
    category: "actinide",
    categoryName: "Aktinida",
    state: "solid",
    group: 3,
    period: 7,
    block: "f",
    shells: [2, 8, 18, 32, 25, 9, 2],
    config: "[Rn] 5f⁷ 6d¹ 7s²",
    electronegativity: 1.28,
    meltingPoint: 1340,
    boilingPoint: 3110,
    density: 13.51,
    discovered: 1944,
    discoverer: "Glenn T. Seaborg, Ralph A. James, Albert Ghiorso",
    summary: "Kurium dinamai untuk menghormati Marie Curie dan Pierre Curie. Digunakan sebagai sumber daya pendorong alfa penjelajah Mars."
  },
  {
    number: 97,
    symbol: "Bk",
    name: "Berkelium",
    latinName: "Berkelium",
    mass: 247,
    category: "actinide",
    categoryName: "Aktinida",
    state: "solid",
    group: 3,
    period: 7,
    block: "f",
    shells: [2, 8, 18, 32, 27, 8, 2],
    config: "[Rn] 5f⁹ 7s²",
    electronegativity: 1.3,
    meltingPoint: 986,
    boilingPoint: 2623,
    density: 14.78,
    discovered: 1949,
    discoverer: "Lawrence Berkeley National Laboratory",
    summary: "Berkelium dinatai dari laboratorium tempat penemuannya di Berkeley, California. Diproduksi dalam jumlah mikrogram."
  },
  {
    number: 98,
    symbol: "Cf",
    name: "Kalifornium",
    latinName: "Californium",
    mass: 251,
    category: "actinide",
    categoryName: "Aktinida",
    state: "solid",
    group: 3,
    period: 7,
    block: "f",
    shells: [2, 8, 18, 32, 28, 8, 2],
    config: "[Rn] 5f¹⁰ 7s²",
    electronegativity: 1.3,
    meltingPoint: 900,
    boilingPoint: 1470,
    density: 15.1,
    discovered: 1950,
    discoverer: "Lawrence Berkeley National Laboratory",
    summary: "Kalifornium-252 adalah pemancar neutron kuat, digunakan untuk mendeteksi retakan struktur logam dan sumur minyak."
  },
  {
    number: 99,
    symbol: "Es",
    name: "Einsteinium",
    latinName: "Einsteinium",
    mass: 252,
    category: "actinide",
    categoryName: "Aktinida",
    state: "solid",
    group: 3,
    period: 7,
    block: "f",
    shells: [2, 8, 18, 32, 29, 8, 2],
    config: "[Rn] 5f¹¹ 7s²",
    electronegativity: 1.3,
    meltingPoint: 860,
    boilingPoint: 996,
    density: 8.84,
    discovered: 1952,
    discoverer: "Lawrence Berkeley National Laboratory",
    summary: "Einsteinium ditemukan dari puing-puing ledakan bom hidrogen 'Ivy Mike' pada tahun 1952, dinamai dari Albert Einstein."
  },
  {
    number: 100,
    symbol: "Fm",
    name: "Fermium",
    latinName: "Fermium",
    mass: 257,
    category: "actinide",
    categoryName: "Aktinida",
    state: "solid",
    group: 3,
    period: 7,
    block: "f",
    shells: [2, 8, 18, 32, 30, 8, 2],
    config: "[Rn] 5f¹² 7s²",
    electronegativity: 1.3,
    meltingPoint: 1527,
    boilingPoint: null,
    density: null,
    discovered: 1952,
    discoverer: "Lawrence Berkeley National Laboratory",
    summary: "Fermium dinamai untuk menghormati Enrico Fermi, pionir fisika nuklir. Merupakan unsur terberat yang dibuat dari penembakan neutron."
  },
  {
    number: 101,
    symbol: "Md",
    name: "Mendelevium",
    latinName: "Mendelevium",
    mass: 258,
    category: "actinide",
    categoryName: "Aktinida",
    state: "solid",
    group: 3,
    period: 7,
    block: "f",
    shells: [2, 8, 18, 32, 31, 8, 2],
    config: "[Rn] 5f¹³ 7s²",
    electronegativity: 1.3,
    meltingPoint: 827,
    boilingPoint: null,
    density: null,
    discovered: 1955,
    discoverer: "Lawrence Berkeley National Laboratory",
    summary: "Mendelevium dinamai dari Dmitri Mendeleev, pencipta Tabel Periodik unsur."
  },
  {
    number: 102,
    symbol: "No",
    name: "Nobelium",
    latinName: "Nobelium",
    mass: 259,
    category: "actinide",
    categoryName: "Aktinida",
    state: "solid",
    group: 3,
    period: 7,
    block: "f",
    shells: [2, 8, 18, 32, 32, 8, 2],
    config: "[Rn] 5f¹⁴ 7s²",
    electronegativity: 1.3,
    meltingPoint: 827,
    boilingPoint: null,
    density: null,
    discovered: 1966,
    discoverer: "Joint Institute for Nuclear Research (JINR)",
    summary: "Nobelium dinamai untuk menghormati Alfred Nobel, penemu dinamit dan pendiri Hadiah Nobel."
  },
  {
    number: 103,
    symbol: "Lr",
    name: "Lawrensium",
    latinName: "Lawrencium",
    mass: 266,
    category: "actinide",
    categoryName: "Aktinida",
    state: "solid",
    group: 3,
    period: 7,
    block: "d",
    shells: [2, 8, 18, 32, 32, 8, 3],
    config: "[Rn] 5f¹⁴ 7s² 7p¹",
    electronegativity: 1.3,
    meltingPoint: 1627,
    boilingPoint: null,
    density: null,
    discovered: 1961,
    discoverer: "Lawrence Berkeley National Laboratory",
    summary: "Lawrensium adalah unsur terakhir dari deret Aktinida sintetis."
  },
  {
    number: 104,
    symbol: "Rf",
    name: "Rutherfordium",
    latinName: "Rutherfordium",
    mass: 267,
    category: "transition-metal",
    categoryName: "Logam Transisi",
    state: "synthetic",
    group: 4,
    period: 7,
    block: "d",
    shells: [2, 8, 18, 32, 32, 10, 2],
    config: "[Rn] 5f¹⁴ 6d² 7s²",
    electronegativity: null,
    meltingPoint: 2100,
    boilingPoint: 5500,
    density: 23.2,
    discovered: 1969,
    discoverer: "JINR, Lawrence Berkeley National Lab",
    summary: "Rutherfordium dinamai dari Ernest Rutherford, bapak fisika nuklir."
  },
  {
    number: 105,
    symbol: "Db",
    name: "Dubnium",
    latinName: "Dubnium",
    mass: 268,
    category: "transition-metal",
    categoryName: "Logam Transisi",
    state: "synthetic",
    group: 5,
    period: 7,
    block: "d",
    shells: [2, 8, 18, 32, 32, 11, 2],
    config: "[Rn] 5f¹⁴ 6d³ 7s²",
    electronegativity: null,
    meltingPoint: null,
    boilingPoint: null,
    density: 29.3,
    discovered: 1970,
    discoverer: "JINR, Lawrence Berkeley National Lab",
    summary: "Dubnium dinamai dari kota Dubna di Rusia, tempat laboratorium riset nuklir terkemuka JINR."
  },
  {
    number: 106,
    symbol: "Sg",
    name: "Seaborgium",
    latinName: "Seaborgium",
    mass: 269,
    category: "transition-metal",
    categoryName: "Logam Transisi",
    state: "synthetic",
    group: 6,
    period: 7,
    block: "d",
    shells: [2, 8, 18, 32, 32, 12, 2],
    config: "[Rn] 5f¹⁴ 6d⁴ 7s²",
    electronegativity: null,
    meltingPoint: null,
    boilingPoint: null,
    density: 35.0,
    discovered: 1974,
    discoverer: "Lawrence Berkeley National Laboratory",
    summary: "Seaborgium dinamai untuk menghormati Glenn T. Seaborg saat beliau masih hidup."
  },
  {
    number: 107,
    symbol: "Bh",
    name: "Bohrium",
    latinName: "Bohrium",
    mass: 270,
    category: "transition-metal",
    categoryName: "Logam Transisi",
    state: "synthetic",
    group: 7,
    period: 7,
    block: "d",
    shells: [2, 8, 18, 32, 32, 13, 2],
    config: "[Rn] 5f¹⁴ 6d⁵ 7s²",
    electronegativity: null,
    meltingPoint: null,
    boilingPoint: null,
    density: 37.1,
    discovered: 1981,
    discoverer: "GSI Helmholtz Centre for Heavy Ion Research",
    summary: "Bohrium dinamai dari fisikawan Denmark Niels Bohr, pencetus teori atom kuantum Bohr."
  },
  {
    number: 108,
    symbol: "Hs",
    name: "Hassium",
    latinName: "Hassium",
    mass: 277,
    category: "transition-metal",
    categoryName: "Logam Transisi",
    state: "synthetic",
    group: 8,
    period: 7,
    block: "d",
    shells: [2, 8, 18, 32, 32, 14, 2],
    config: "[Rn] 5f¹⁴ 6d⁶ 7s²",
    electronegativity: null,
    meltingPoint: null,
    boilingPoint: null,
    density: 40.7,
    discovered: 1984,
    discoverer: "GSI Helmholtz Centre for Heavy Ion Research",
    summary: "Hassium dinamai dari negara bagian Hesse (Hassia) di Jerman."
  },
  {
    number: 109,
    symbol: "Mt",
    name: "Meitnerium",
    latinName: "Meitnerium",
    mass: 278,
    category: "transition-metal",
    categoryName: "Logam Transisi",
    state: "synthetic",
    group: 9,
    period: 7,
    block: "d",
    shells: [2, 8, 18, 32, 32, 15, 2],
    config: "[Rn] 5f¹⁴ 6d⁷ 7s²",
    electronegativity: null,
    meltingPoint: null,
    boilingPoint: null,
    density: 37.4,
    discovered: 1982,
    discoverer: "GSI Helmholtz Centre for Heavy Ion Research",
    summary: "Meitnerium dinamai dari Lise Meitner, fisikawan penemu pembelahan inti (fisi nuklir)."
  },
  {
    number: 110,
    symbol: "Ds",
    name: "Darmstadtium",
    latinName: "Darmstadtium",
    mass: 281,
    category: "transition-metal",
    categoryName: "Logam Transisi",
    state: "synthetic",
    group: 10,
    period: 7,
    block: "d",
    shells: [2, 8, 18, 32, 32, 17, 1],
    config: "[Rn] 5f¹⁴ 6d⁹ 7s¹",
    electronegativity: null,
    meltingPoint: null,
    boilingPoint: null,
    density: 34.8,
    discovered: 1994,
    discoverer: "GSI Helmholtz Centre for Heavy Ion Research",
    summary: "Darmstadtium dinamai dari kota Darmstadt di Jerman."
  },
  {
    number: 111,
    symbol: "Rg",
    name: "Roentgenium",
    latinName: "Roentgenium",
    mass: 282,
    category: "transition-metal",
    categoryName: "Logam Transisi",
    state: "synthetic",
    group: 11,
    period: 7,
    block: "d",
    shells: [2, 8, 18, 32, 32, 18, 1],
    config: "[Rn] 5f¹⁴ 6d¹⁰ 7s¹",
    electronegativity: null,
    meltingPoint: null,
    boilingPoint: null,
    density: 28.7,
    discovered: 1994,
    discoverer: "GSI Helmholtz Centre for Heavy Ion Research",
    summary: "Roentgenium dinamai untuk menghormati Wilhelm Röntgen, penemu Sinar-X."
  },
  {
    number: 112,
    symbol: "Cn",
    name: "Kopernisium",
    latinName: "Copernicium",
    mass: 285,
    category: "transition-metal",
    categoryName: "Logam Transisi",
    state: "synthetic",
    group: 12,
    period: 7,
    block: "d",
    shells: [2, 8, 18, 32, 32, 18, 2],
    config: "[Rn] 5f¹⁴ 6d¹⁰ 7s²",
    electronegativity: null,
    meltingPoint: null,
    boilingPoint: 357,
    density: 14.0,
    discovered: 1996,
    discoverer: "GSI Helmholtz Centre for Heavy Ion Research",
    summary: "Kopernisium dinamai untuk menghormati Nicolaus Copernicus, pencetus teori heliosentris tata surya."
  },
  {
    number: 113,
    symbol: "Nh",
    name: "Nihonium",
    latinName: "Nihonium",
    mass: 286,
    category: "post-transition",
    categoryName: "Pasca-Transisi",
    state: "synthetic",
    group: 13,
    period: 7,
    block: "p",
    shells: [2, 8, 18, 32, 32, 18, 3],
    config: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p¹",
    electronegativity: null,
    meltingPoint: 430,
    boilingPoint: 1130,
    density: 16,
    discovered: 2004,
    discoverer: "RIKEN Nishina Center (Jepang)",
    summary: "Nihonium adalah unsur sintetis pertama yang ditemukan di Asia (Jepang, 'Nihon')."
  },
  {
    number: 114,
    symbol: "Fl",
    name: "Flerovium",
    latinName: "Flerovium",
    mass: 289,
    category: "post-transition",
    categoryName: "Pasca-Transisi",
    state: "synthetic",
    group: 14,
    period: 7,
    block: "p",
    shells: [2, 8, 18, 32, 32, 18, 4],
    config: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p²",
    electronegativity: null,
    meltingPoint: 67,
    boilingPoint: 147,
    density: 9.93,
    discovered: 1998,
    discoverer: "JINR Dubna & LLNL",
    summary: "Flerovium dinamai dari Flerov Laboratory of Nuclear Reactions."
  },
  {
    number: 115,
    symbol: "Mc",
    name: "Moskovium",
    latinName: "Moscovium",
    mass: 290,
    category: "post-transition",
    categoryName: "Pasca-Transisi",
    state: "synthetic",
    group: 15,
    period: 7,
    block: "p",
    shells: [2, 8, 18, 32, 32, 18, 5],
    config: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p³",
    electronegativity: null,
    meltingPoint: 400,
    boilingPoint: 1100,
    density: 13.5,
    discovered: 2003,
    discoverer: "JINR Dubna & LLNL",
    summary: "Moskovium dinamai untuk menghormati Moscow Oblast di Rusia."
  },
  {
    number: 116,
    symbol: "Lv",
    name: "Livermorium",
    latinName: "Livermorium",
    mass: 293,
    category: "post-transition",
    categoryName: "Pasca-Transisi",
    state: "synthetic",
    group: 16,
    period: 7,
    block: "p",
    shells: [2, 8, 18, 32, 32, 18, 6],
    config: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁴",
    electronegativity: null,
    meltingPoint: 435,
    boilingPoint: 820,
    density: 12.9,
    discovered: 2000,
    discoverer: "Lawrence Livermore National Laboratory & JINR",
    summary: "Livermorium dinamai dari kota Livermore, California, lokasi Lawrence Livermore National Lab."
  },
  {
    number: 117,
    symbol: "Ts",
    name: "Tenesis",
    latinName: "Tennessine",
    mass: 294,
    category: "halogen",
    categoryName: "Halogen",
    state: "synthetic",
    group: 17,
    period: 7,
    block: "p",
    shells: [2, 8, 18, 32, 32, 18, 7],
    config: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁵",
    electronegativity: null,
    meltingPoint: 450,
    boilingPoint: 610,
    density: 7.2,
    discovered: 2010,
    discoverer: "Oak Ridge National Laboratory, Vanderbilt Univ, JINR",
    summary: "Tenesis dinamai dari negara bagian Tennessee di AS atas kontribusi riset nuklirnya."
  },
  {
    number: 118,
    symbol: "Og",
    name: "Oganeson",
    latinName: "Oganesson",
    mass: 294,
    category: "noble-gas",
    categoryName: "Gas Mulia",
    state: "synthetic",
    group: 18,
    period: 7,
    block: "p",
    shells: [2, 8, 18, 32, 32, 18, 8],
    config: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁶",
    electronegativity: null,
    meltingPoint: 50,
    boilingPoint: 80,
    density: 5.0,
    discovered: 2002,
    discoverer: "JINR Dubna & LLNL",
    summary: "Oganeson adalah unsur terberat pada Tabel Periodik saat ini (nomor atom 118), dinamai dari fisikawan Yuri Oganessian."
  }
];
